#!/usr/bin/env perl
##============================================================================##
## description  latexmk config file
## author       Hengda Shi
## created_at   07/30/2020
## modified_at  07/30/2020
##============================================================================##
## latex commands; %S: src, %O: option, %D: dest, %B: src without extension
# $xelatex =~ s/^xelatex/xelatex --shell-escape -halt-on-error -interaction=nonstopmode -synctex=1/;
$xelatex    = 'xelatex --shell-escape -halt-on-error -interaction=nonstopmode -synctex=1 %O %S';
$max_repeat = 5;
##============================================================================##
## pdf mode
$pdf_mode   = 5; # 0: none, 1: pdflatex, 2: ps2pdf, 3: dvipdf
##============================================================================##
## cleanup extensions
$clean_ext = "vrb xdv synctex.gz nav snm fls";
##============================================================================##
## avoid log linebreaks; see https://tex.stackexchange.com/questions/384133/
$ENV{max_print_line} = $log_wrap = 10000;
##============================================================================##
## viewer settings
$pvc_view_file_via_temporary = 0;
if ($^O eq 'darwin') {
    # OSX
    $pdf_previewer = 'zathura';
} elsif ($^O eq 'linux') {
    # Linux
}
##============================================================================##
